
quotes = [
    "Un buen drama es como la vida, pero sin las partes aburridas. - Alfred Hitchcock",
    "El cine no es un trozo de vida sino un pedazo de pastel.  - Alfred Hitchcock",
    "El cine no es para mí un medio para escapar de la realidad. Es un medio para acercarme a ella.  - Wim Wenders",
    "Haz que cada plano sea tan hermoso como un poema.  - Wong Kar-wai",
    "Si hubiera hecho “Cenicienta” la gente hubiera buscado un cadáver en el coche de caballos. - Alfred Hitchcock ",
    "Cada película es un sueño. - David Lynch ",
    "No me gusta dar entrevistas. Siempre hay el peligro de que te citen mal o, peor aún, de que citen exactamente lo que dijiste. - Stanley Kubrick ",
    "Si puede ser escrito o pensado, puede ser filmado. - Stanley Kubrick ",
    "A fin de cuentas, todo es un chiste. - Charlie Chaplin ",
    "A la luz de nuestros egos, todos somos monarcas destronados. - Charlie Chaplin",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
]